name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pandoc/actions/setup@v1
        with:
          version: 2.19
      - run: pandoc -s -o index.html index.md
